global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'oggole-monitor'

scrape_configs:
  # Monitor Prometheus itself
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']

  # Monitor Oggole App
  - job_name: 'oggole-app'
    scrape_interval: 5s
    static_configs:
      - targets: ['20.254.43.177:8080']
        labels:
          environment: 'production'
          application: 'oggole'
